name: Rss2TG
on:
  schedule:
    - cron: '0 */8 * * *'
#env:
#  TZ: Asia/Shanghai

jobs:
    search-and-push:
        runs-on: ubuntu-latest
        steps:
        - name: Install Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.16.x
        - name: Checkout code
          uses: actions/checkout@v2
        - name: build
          run: go run main.go --tg_token=${{secrets.tg_token}} --tg_channel=${{secrets.CHANNELID}}