name: Feed2TG
on:
  schedule:
    - cron: '0 */1 * * *'
#env:
#  TZ: Asia/Shanghai

jobs:
    search-and-push:
        runs-on: ubuntu-latest
        steps:
        - name: Install Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.16.x
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Reuse Cache
          uses: actions/cache@v2
          id: feed-cache
          with:
            path: /var/cache/feed2tg
            key: ${{ runner.os }}-feed-cache
        - name: build
          run: go run main.go --tg_token=${{secrets.TG_TOKEN}} --tg_channel=${{secrets.TG_CHANNEL}} --cache=/var/cache/feed2tg --proxy=
